### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by fredthedead** [tan-zx/substack-archives-downloader#11]
I'm getting the majority of the PDFs containing one line saying, 'Too many requests'. I tried adding a sleep method in the while loop in this function `_load_articles_in_date_range` but that didn't solve it.

Any other suggestions please?

**Comment by ddaines** [comment]
Same issue. Can't figure out why the sleep method didn't solve it.

**Comment by ddaines** [comment]
> I'm getting the majority of the PDFs containing one line saying, 'Too many requests'. I tried adding a sleep method in the while loop in this function `_load_articles_in_date_range` but that didn't solve it.
> 
> Any other suggestions please?

I figured it out. The sleep method belongs in _convert_article_tuples_to_pdfs(), where the individual downloads actually occur.

Add something like this:
`time.sleep(randint(5,10))`

**Comment by fredthedead** [comment]
Brilliant, that solved it! thank you @ddaines++++

**Comment by tan-zx** [comment]
wanna open a PR so I can merge the change in? :)
