### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by 0to1123** [tan-zx/substack-archives-downloader#12]
I’m using the main.py  to convert Substack posts to pdf. Unfortunately, it’s failing, with "Too Many Requests" content files.
![Too Many Requests](https://user-images.githubusercontent.com/64362725/229769366-7265aca4-251b-4070-95d0-ff63f33f538e.png)

**Comment by alpreu** [comment]
In `/downloaders/substack_archives_downloader.py` just add a `time.sleep(2)` at the end of the `_convert_article_tuples_to_pdfs` method to throttle the requests ;)

**Comment by 0to1123** [comment]
Thank @alpreu for your response.

But my terminal shown that:
 "name 'time' is not defined
We're sorry, something has gone wrong."

Could you give me exactly code for my issue?

Thank you again, bro

**Comment by 0to1123** [comment]
@alpreu thank you, let me try, <3
